language: php
php:
  - '7.2'
services:
  - postgresql
env:
  global:
    - DB_HOST=localhost
    - DB_PORT=5432
    - DB_DATABASE=travis-db-test
    - DB_USERNAME=postgres
    - DB_PASSWORD=
before_script:
  - psql -U postgres -c 'create database "travis-db-test";'
  - psql -U postgres travis-db-test -c 'create extension "uuid-ossp";'
  - composer install --prefer-source
script: phpunit